import { NextResponse } from "next/server"
import { createClient } from "@/lib/supabase/server"

export async function POST(request: Request) {
  const secret = process.env.TELEGRAM_WEBHOOK_SECRET
  if (secret && request.headers.get("x-telegram-bot-api-secret-token") !== secret) {
    return NextResponse.json({ ok: false }, { status: 401 })
  }
  const update = await request.json()
  const message = update.message
  const chatId = message?.chat?.id
  const text = String(message?.text || "").trim()
  if (!chatId) return NextResponse.json({ ok: true })

  // Linking is completed through a signed /start payload generated by the dashboard.
  if (text.startsWith("/start ")) {
    const token = text.slice(7).trim()
    const supabase = await createClient()
    const { data: link } = await supabase.from("ashqe_telegram_connections").select("user_id").eq("chat_id", token).maybeSingle()
    if (link) return NextResponse.json({ ok: true })
  }

  const botToken = process.env.TELEGRAM_BOT_TOKEN
  if (!botToken) return NextResponse.json({ ok: true })

  const response = text === "/brief"
    ? "Your Ashqe brief is ready in the dashboard. Connect a Telegram webhook and AI provider to enable live scheduled briefs."
    : "Ashqe is connected. Try /brief."
  await fetch(`https://api.telegram.org/bot${botToken}/sendMessage`, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({ chat_id: chatId, text: response }),
  })
  return NextResponse.json({ ok: true })
}
